# سيؤدي سير العمل هذا إلى إنشاء مشروع Swift
# لمزيد من المعلومات انظر: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

اختبار سريع -v: اسم

على:
  يدفع:
    الفروع: [ "الرئيسي" ]
  طلب سحب:
    الفروع: [ "الرئيسي" ]

وظائف:
  بناء:

    يعمل على: ماكوس-الأحدث

    خطوات:
    - الاستخدامات: الإجراءات/checkout@v4
    - اسم: بناء
      الركض: بناء سريع -v
    - اسم: تشغيل الاختبارات
      run: swift test -v
